spring.application.name=tvmaze

server.port=8080

tvmaze.url=https://api.tvmaze.com

spring.mongodb.uri=mongodb+srv://tvMazeEvaluacion:prueba317@tvmaze-evaluacion.cmgarx3.mongodb.net/tvmaze?appName=tvmaze-evaluacion